### ISSUE TITLE
Clarification on usage

### ISSUE THREAD

**Issue by mr-september** [bagrow/portrait-divergence#4]
1. ReadMe's Basic example:
`python portrait_divergence.py data/net1.edgelist data/net2.edgelist`

Is that a file type with the extension literally being `.edgelist`?
If no, what's the exact expected format? TSV/CSV? Header or no header?

2. Example files in the `Data` folder aren't like any edge lists I've seen before. I'm used to files like
`"String1" "String2" "EdgeWeight"`, but the example files are `"Number1" "Number2" "{}"`? 

3. After running the above code, is one number the only output? Will the script make a new folder and write output files, with the Portrait diagrams, etc?

**Comment by mr-september** [comment]
To answer my own questions...
1. `.edgelist` files are simply space separated txt files, with extension renamed.
2. Doesn't matter
3. I could get the output number, but still no idea how to generate the portrait.

**Comment by bagrow** [comment]
> 3. I could get the output number, but still no idea how to generate the portrait.

You can get the portrait as a matrix by writing code to [call `portrait(graph)`](https://github.com/bagrow/network-portrait-divergence/blob/b6fdfbb607ffadbd60dccc2f7ae306351611a1a4/portrait_divergence.py#L47).

Hope this helps.

**Comment by mr-september** [comment]
Sorry need a little extra help on this one. Is the input supposed to be in the same `.edgelist` format as the original `python portrait_divergence.py data/net1.edgelist data/net2.edgelist`?

Because this is returning an error:

```
from portrait_divergence import portrait_py

portrait_py("...blabla/edgelists/edgelist1.edgelist")
```
```
Traceback (most recent call last):
  File "...blabla/NPD/Paint Portrait.py", line 32, in <module>
    portrait_py(query_file)
  File "...blabla/NPD/portrait_divergence.py", line 54, in portrait_py
    N = graph.number_of_nodes()
AttributeError: 'str' object has no attribute 'number_of_nodes'
```
