### ISSUE TITLE
Clarification on Network Portrait

### ISSUE THREAD

**Issue by Firedrops** [bagrow/portrait-divergence#5]
Hi, this is regarding Fig 1 in your publication.

I am trying to properly understand the Portraits, but am feeling lost.

1. The left hand side Y-axis is the "path length", so
2. Row 0 encodes the number of nodes. Next is where it gets confusing:
3. The bottom X-axis is also labelled as the "number of nodes _k_"? Does this exclude row 0, which is "doing its own thing"? 
4. In the examples, it's either at 0 or 1 position according to the bottom axis, while the networks above clearly show >1 nodes for each example. But they're all bright yellow, 
5. So it looks like the blue-yellow gradient legend on the right represents the number of nodes?
4. In that case, what does the bottom X-axis "number of nodes _k_" refer to?

**Comment by bagrow** [comment]
The elements of matrix B are defined such that the d,k element B_{d,k} = the number of nodes that have exactly k nodes d steps away. The x-axis is k, which is a number of nodes. The values in the matrix are also numbers of nodes.

Every node has exactly one node zero steps away, themselves. So for d = 0, all entries in that row are zero except k = 1, and B_{0,1} = N, where N is the number of nodes in the graph. This entry is visible in the upper-left corner of the three plots in Fig 1. 

The colorbars represent the entries in the matrix. The largest value for an entry is N and B_{0,1} will have that value.

**Comment by Firedrops** [comment]
> The x-axis is k, which is a number of nodes. The values in the matrix are also numbers of nodes.

I think this is where the confusion stems. What's the difference between the number of nodes k vs values in the matrix?

The way I understand it is the values in the matrix (B) is the sum of nodes which have path lengths l to k other nodes?

Also, is path length l the minimum distance? In a fully connected 3-node graph, 

Will there be a "3" in row 3 (l=2) column 3(k=2)? Or will it all be 0s, and hence the Portrait Matrix y-axis maxes out at l=1?

**Comment by bagrow** [comment]
Each node is chosen as a _starting_ node and the shortest path length from that starting node to every other node is computed. As a concrete example, suppose B_{2,3} = 5. That means there are five _starting_ nodes with three nodes two steps away. Likewise, B_{2,4} = 7 means there are 7 _starting_ nodes with four nodes two steps away.
